In [ ]:
# import sys
# from pathlib import Path

# sys.path.append(str(Path("..").resolve()))

# DATA_FILE = "../inputs/synthetic_chase_statement_2025_final.csv"

In [ ]:
# from src.data_loader import load_transactions_csv

# df = load_transactions_csv(DATA_FILE)

# df.head()

  Details        Date                  Description   Amount      Category
0   DEBIT  01/01/2025  ACH DEBIT GREYSTAR PROPERTY -3000.00       Housing
1   DEBIT  01/02/2025                     NIKE.COM   -60.96      Shopping
2   DEBIT  01/02/2025              OPENAI *CHATGPT   -20.00  Subscription
3   DEBIT  01/04/2025                SAFEWAY #1831   -90.10       Grocery
4   DEBIT  01/05/2025              DOORDASH INC CA   -29.75        Dining

In [ ]:
# from src.preprocessing import MERCHANT_MAPPING, preprocess_transactions

# processed_df = preprocess_transactions(df)
# processed_df.head()
# processed_df.info()
# print("--------------------------------")
# print("Missing values:")
# processed_df.isna().sum()
# print("--------------------------------")
# mapped_merchants = set(MERCHANT_MAPPING.keys())
# unmapped_df = processed_df[
#     ~processed_df["Merchant"].isin(mapped_merchants)
# ]
# print(f"Number of unmapped transactions: {len(unmapped_df)}")
# print(f"Number of unique unmapped merchants: {unmapped_df['Merchant'].nunique()}")

# unmapped_df[
#     ["Description", "Merchant"]
# ].drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         883 non-null    datetime64[ns]
 1   Description  883 non-null    object
 2   Merchant     883 non-null    object
 3   Amount       883 non-null    float64
 4   Category     883 non-null    object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 34.6+ KB
--------------------------------
Missing values:
--------------------------------
Number of unmapped transactions: 0
Number of unique unmapped merchants: 0

Empty DataFrame
Columns: [Description, Merchant]
Index: []